package brief

import (
	"bytes"
	"reflect"
	"strings"
	"testing"

	"github.com/tpisel/memento/internal/manifest"
	"github.com/tpisel/memento/internal/markdown"
)

func TestRenderProducesDeterministicMarkdownProjection(t *testing.T) {
	m := manifest.Manifest{
		SchemaVersion: manifest.CurrentSchemaVersion,
		Entries: []manifest.Entry{
			{
				Key:     "Architecture decision record/adr-0002.md",
				Title:   "ADR 0002",
				Summary: "Second ADR.",
				Bytes:   222,
				Lines:   12,
				Tags:    []string{"brief"},
				Mode:    markdown.ModeAppendOnly,
			},
			{
				Key:     "notes/beta.md",
				Title:   "Beta",
				Summary: "A compact note.",
				Bytes:   1234,
				Lines:   7,
				Tags:    []string{"brief"},
				Mode:    markdown.ModeAppendOnly,
			},
			{
				Key:     "Architecture decision record/adr-0001.md",
				Title:   "ADR 0001",
				Summary: "First ADR.",
				Bytes:   111,
				Lines:   11,
				Tags:    []string{"memento"},
				Mode:    markdown.ModeAppendOnly,
			},
			{
				Key:     "zeta.md",
				Title:   "Alpha <Beta>",
				Summary: "Summary with <angle> & ampersand.",
				Bytes:   342,
				Lines:   32,
				Tags:    []string{"memento", "brief"},
				Mode:    markdown.ModeReadOnly,
				Headings: []manifest.Heading{
					{Level: 2, Text: "Context", Slug: "context"},
					{Level: 3, Text: "Decision & Tradeoffs", Slug: "decision-tradeoffs"},
				},
				SummaryState: markdown.SummaryStale,
				Links: manifest.Links{
					Out: []manifest.OutLink{{Target: "other.md", Type: "wiki", Resolved: true}},
				},
			},
			{
				Key:     "notes/gamma.md",
				Title:   "Gamma",
				Summary: "A larger note.",
				Bytes:   12345,
				Lines:   250,
				Tags:    []string{"memento"},
				Mode:    markdown.ModeAppendOnly,
			},
			{
				Key:          "empty.md",
				Title:        "Zeta",
				Summary:      "",
				Tags:         []string{},
				Mode:         markdown.ModeAppendOnly,
				SummaryState: markdown.SummaryMissing,
			},
		},
		Tags: map[string]int{
			"brief":   2,
			"memento": 2,
		},
	}

	first := Render(m)
	second := Render(m)
	if !bytes.Equal(first, second) {
		t.Fatalf("Render output changed between runs:\nfirst:\n%s\nsecond:\n%s", first, second)
	}

	want := `---
mode: read-only
manifest: sha256:addc10f0f2a8f05639b2273fee70615a4d08ef00a72eae033ec65453e80e867f
---
> [!caution] Auto-generated by ` + "`memento compile`" + `
> Any edits to this file will be overwritten on the next compile run.

# Memento Brief

## (root)

### @1. Zeta

key: ` + "`empty.md`" + ` | mode: ` + "`append-only`" + ` | size: 0B / 0 lines | [unsummarised]

### @2. Alpha <Beta>

key: ` + "`zeta.md`" + ` | mode: ` + "`read-only`" + ` | tags: ` + "`brief`" + `, ` + "`memento`" + ` | size: 342B / 32 lines | [stale-summary]

Summary with <angle> & ampersand.

Headings: Context; Decision & Tradeoffs

## Architecture decision record

### @3. ADR 0001

key: ` + "`Architecture decision record/adr-0001.md`" + ` | mode: ` + "`append-only`" + ` | tags: ` + "`memento`" + ` | size: 111B / 11 lines

First ADR.

### @4. ADR 0002

key: ` + "`Architecture decision record/adr-0002.md`" + ` | mode: ` + "`append-only`" + ` | tags: ` + "`brief`" + ` | size: 222B / 12 lines

Second ADR.

## notes

### @5. Beta

key: ` + "`notes/beta.md`" + ` | mode: ` + "`append-only`" + ` | tags: ` + "`brief`" + ` | size: 1.2k / 7 lines

A compact note.

### @6. Gamma

key: ` + "`notes/gamma.md`" + ` | mode: ` + "`append-only`" + ` | tags: ` + "`memento`" + ` | size: 12k / 250 lines

A larger note.

---

Staleness: 1 stale, 1 unsummarised
Tag frequency: brief=2, memento=2
Section read: memento read <key|@N>#<heading>
`
	if string(first) != want {
		t.Fatalf("Render() =\n%s\nwant:\n%s", first, want)
	}

	if !bytes.Contains(first, []byte("> [!caution]")) {
		t.Fatalf("Render() missing Obsidian callout marker:\n%s", first)
	}

	for _, forbidden := range []string{"<!-- Auto-generated", "summary_stale", "links", "slug", "\\u003c", "\\u003e", "\\u0026"} {
		if bytes.Contains(first, []byte(forbidden)) {
			t.Fatalf("Render() contains forbidden %q:\n%s", forbidden, first)
		}
	}
}

func TestRenderContractSectionsAppearOnceInDocumentedOrder(t *testing.T) {
	m := manifest.Manifest{
		SchemaVersion: manifest.CurrentSchemaVersion,
		Entries: []manifest.Entry{
			{
				Key:     "root.md",
				Title:   "Root",
				Summary: "Links out to [[folder/target]].",
				Bytes:   10,
				Lines:   1,
				Tags:    []string{"alpha"},
				Mode:    markdown.ModeAppendOnly,
				Links: manifest.Links{
					Out: []manifest.OutLink{
						{Target: "folder/target.md", Type: "wiki", Resolved: true},
						{Target: "missing", Type: "wiki", Resolved: false},
					},
				},
			},
			{
				Key:     "folder/target.md",
				Title:   "Target",
				Summary: "Target summary.",
				Bytes:   20,
				Lines:   2,
				Tags:    []string{"beta"},
				Mode:    markdown.ModeReadOnly,
				Headings: []manifest.Heading{
					{Level: 2, Text: "Context", Slug: "context"},
				},
				Links: manifest.Links{
					In: []manifest.InLink{{Source: "root.md", Type: "wiki"}},
				},
			},
		},
		Tags: map[string]int{"alpha": 1, "beta": 1},
	}

	got := string(Render(m))
	ordered := []string{
		"---\nmode: read-only\nmanifest: sha256:",
		Banner,
		"# Memento Brief",
		"## (root)",
		"### @1. Root",
		"key: `root.md` | mode: `append-only` | tags: `alpha` | size: 10B / 1 lines",
		"Links out to [[folder/target|folder/target @2]].",
		"## folder",
		"### @2. Target",
		"key: `folder/target.md` | mode: `read-only` | tags: `beta` | size: 20B / 2 lines",
		"Headings: Context",
		"---\n\nTag frequency: alpha=1, beta=1\n",
		"Section read: memento read <key|@N>#<heading>\n",
	}

	last := -1
	for _, marker := range ordered {
		if strings.Count(got, marker) != 1 {
			t.Fatalf("Render() marker %q appears %d times, want once:\n%s", marker, strings.Count(got, marker), got)
		}
		next := strings.Index(got, marker)
		if next <= last {
			t.Fatalf("Render() marker %q appears out of order:\n%s", marker, got)
		}
		last = next
	}
}

func TestRenderMarksMissingFallbackSummaryAndOmitsZeroStalenessFooter(t *testing.T) {
	missing := manifest.Manifest{
		SchemaVersion: manifest.CurrentSchemaVersion,
		Entries: []manifest.Entry{
			{
				Key:          "missing.md",
				Title:        "Missing",
				Summary:      "First paragraph fallback.",
				Mode:         markdown.ModeAppendOnly,
				SummaryState: markdown.SummaryMissing,
			},
		},
	}
	gotMissing := string(Render(missing))
	for _, want := range []string{
		"key: `missing.md` | mode: `append-only` | size: 0B / 0 lines | [unsummarised]",
		"First paragraph fallback.",
		"Staleness: 0 stale, 1 unsummarised\n",
	} {
		if !strings.Contains(gotMissing, want) {
			t.Fatalf("Render(missing) =\n%s\nwant %q", gotMissing, want)
		}
	}

	current := manifest.Manifest{
		SchemaVersion: manifest.CurrentSchemaVersion,
		Entries: []manifest.Entry{
			{
				Key:          "current.md",
				Title:        "Current",
				Summary:      "Committed summary.",
				Mode:         markdown.ModeAppendOnly,
				SummaryState: markdown.SummaryCurrent,
			},
		},
	}
	gotCurrent := string(Render(current))
	if strings.Contains(gotCurrent, "Staleness:") {
		t.Fatalf("Render(current) =\n%s\nwant no staleness footer", gotCurrent)
	}
	if strings.Contains(gotCurrent, "stale-summary") || strings.Contains(gotCurrent, "unsummarised") {
		t.Fatalf("Render(current) =\n%s\nwant no summary markers", gotCurrent)
	}
}

func TestRenderMarksUnparsedModeVisibly(t *testing.T) {
	// A note whose frontmatter failed to parse carries the ModeUnparsed sentinel.
	// The brief must surface it with a loud ⚠ marker so an author can see the note
	// is silently held read-only by a parse error, not mistake it for a declared
	// mode (memento-o0a).
	m := manifest.Manifest{
		SchemaVersion: manifest.CurrentSchemaVersion,
		Entries: []manifest.Entry{
			{
				Key:          "broken.md",
				Title:        "Broken",
				Mode:         markdown.ModeUnparsed,
				SummaryState: markdown.SummaryMissing,
			},
		},
	}
	got := string(Render(m))
	if !strings.Contains(got, "mode: ⚠ unparsed") {
		t.Fatalf("Render() =\n%s\nwant a ⚠ unparsed mode marker", got)
	}
	// The bare sentinel token must not render as if it were a declared mode.
	if strings.Contains(got, "mode: `unparsed`") {
		t.Fatalf("Render() =\n%s\nrendered the sentinel as a declared mode, want the ⚠ marker", got)
	}
}

func TestNumberedEntriesArePureAndDeterministic(t *testing.T) {
	m := manifest.Manifest{
		Entries: []manifest.Entry{
			{Key: "b/two.md", Title: "Two"},
			{Key: "a/b/three.md", Title: "Three"},
			{Key: "root.md", Title: "Root"},
			{Key: "a/one.md", Title: "One"},
		},
	}

	first := NumberedEntries(m)
	second := NumberedEntries(m)

	want := []struct {
		number int
		folder string
		key    string
	}{
		{1, "(root)", "root.md"},
		{2, "a", "a/one.md"},
		{3, "a/b", "a/b/three.md"},
		{4, "b", "b/two.md"},
	}
	if len(first) != len(want) {
		t.Fatalf("NumberedEntries() len = %d, want %d: %#v", len(first), len(want), first)
	}
	if len(second) != len(want) {
		t.Fatalf("NumberedEntries() second len = %d, want %d: %#v", len(second), len(want), second)
	}
	for i := range want {
		if first[i].Number != want[i].number || first[i].Folder != want[i].folder || first[i].Entry.Key != want[i].key {
			t.Fatalf("NumberedEntries()[%d] = %#v, want number=%d folder=%q key=%q", i, first[i], want[i].number, want[i].folder, want[i].key)
		}
		if !reflect.DeepEqual(second[i], first[i]) {
			t.Fatalf("NumberedEntries() changed between runs:\nfirst=%#v\nsecond=%#v", first, second)
		}
	}
}

func TestRenderSuffixesResolvedSummaryWikiLinksWithEntryNumbers(t *testing.T) {
	m := manifest.Manifest{
		SchemaVersion: manifest.CurrentSchemaVersion,
		Entries: []manifest.Entry{
			{
				Key:   "alpha.md",
				Title: "Alpha",
				Summary: "Resolved [[beta]], display [[beta|Beta note]], broken [[missing]], " +
					"and anchored [[beta#Decision]] links.",
				Mode: markdown.ModeAppendOnly,
			},
			{
				Key:     "beta.md",
				Title:   "Beta",
				Summary: "Target.",
				Mode:    markdown.ModeAppendOnly,
			},
		},
	}

	got := string(Render(m))
	for _, want := range []string{
		"Resolved [[beta|beta @2]], display [[beta|Beta note @2]], broken [[missing]], and anchored [[beta#Decision]] links.",
		"Target.",
	} {
		if !bytes.Contains([]byte(got), []byte(want)) {
			t.Fatalf("Render() =\n%s\nwant %q", got, want)
		}
	}
}

func TestRenderDoesNotSurfaceOperationalToolFiles(t *testing.T) {
	got := string(Render(manifest.Manifest{SchemaVersion: manifest.CurrentSchemaVersion}))

	for _, forbidden := range []string{"Tool files:", "_memento/", "audit.md", "review.md", "writing.md"} {
		if strings.Contains(got, forbidden) {
			t.Fatalf("Render() surfaces operational tool file marker %q, want it absent (ADR-0030):\n%s", forbidden, got)
		}
	}
}

func TestFriendlyBytes(t *testing.T) {
	tests := map[int64]string{
		0:       "0B",
		342:     "342B",
		1234:    "1.2k",
		12345:   "12k",
		1400000: "1.4M",
	}

	for bytes, want := range tests {
		if got := friendlyBytes(bytes); got != want {
			t.Fatalf("friendlyBytes(%d) = %q, want %q", bytes, got, want)
		}
	}
}
