package brief

import (
	"bytes"
	"crypto/sha256"
	"errors"
	"fmt"
	"os"
	"path"
	"path/filepath"
	"sort"
	"strings"

	"github.com/tpisel/memento/internal/manifest"
	"github.com/tpisel/memento/internal/vault"
)

const Banner = "> [!caution] Auto-generated by `memento compile`\n> Any edits to this file will be overwritten on the next compile run."
const RootFolder = "(root)"

var toolConsumedFileNames = []string{"audit.md", "review.md", "writing.md"}

type NumberedEntry struct {
	Number int
	Folder string
	Entry  manifest.Entry
}

// DetectToolFiles returns known tool-consumed files present in the vault's
// human-readable tool namespace.
func DetectToolFiles(v vault.Vault) ([]string, error) {
	dir := filepath.Join(v.Root, vault.ToolDirName)
	info, err := os.Stat(dir)
	if err != nil {
		if errors.Is(err, os.ErrNotExist) {
			return nil, nil
		}
		return nil, fmt.Errorf("stat %s: %w", vault.ToolDirName, err)
	}
	if !info.IsDir() {
		return nil, nil
	}

	files := []string{}
	for _, name := range toolConsumedFileNames {
		path := filepath.Join(dir, name)
		info, err := os.Stat(path)
		if err != nil {
			if errors.Is(err, os.ErrNotExist) {
				continue
			}
			return nil, fmt.Errorf("stat %s: %w", filepath.ToSlash(filepath.Join(vault.ToolDirName, name)), err)
		}
		if info.IsDir() {
			continue
		}
		files = append(files, filepath.ToSlash(filepath.Join(vault.ToolDirName, name)))
	}
	return files, nil
}

// NumberedEntries returns the brief ordering with stable render-time numeric
// references. Numbers are a projection only; manifest entries are unchanged.
func NumberedEntries(m manifest.Manifest) []NumberedEntry {
	entries := append([]manifest.Entry(nil), m.Entries...)
	sort.Slice(entries, func(i, j int) bool {
		iFolder, iName := splitKey(entries[i].Key)
		jFolder, jName := splitKey(entries[j].Key)
		iFolderKey := folderSortKey(iFolder)
		jFolderKey := folderSortKey(jFolder)
		if iFolderKey != jFolderKey {
			return iFolderKey < jFolderKey
		}
		if iName != jName {
			return iName < jName
		}
		return entries[i].Key < entries[j].Key
	})

	numbered := make([]NumberedEntry, 0, len(entries))
	for i, entry := range entries {
		folder, _ := splitKey(entry.Key)
		numbered = append(numbered, NumberedEntry{
			Number: i + 1,
			Folder: folder,
			Entry:  entry,
		})
	}
	return numbered
}

// Render returns the agent-facing markdown projection of a manifest.
func Render(m manifest.Manifest) []byte {
	return RenderWithToolFiles(m, nil)
}

// RenderWithToolFiles returns the agent-facing markdown projection of a manifest
// and includes detected tool-consumed files in the footer.
func RenderWithToolFiles(m manifest.Manifest, toolFiles []string) []byte {
	var b bytes.Buffer
	fmt.Fprintf(&b, "---\nmode: read-only\nmanifest: %s\n---\n", ManifestHash(m))
	b.WriteString(Banner)
	b.WriteString("\n\n# Memento Brief\n")

	numberedEntries := NumberedEntries(m)
	numberByKey := map[string]int{}
	for _, numbered := range numberedEntries {
		numberByKey[numbered.Entry.Key] = numbered.Number
	}
	linkResolver := manifest.NewWikiLinkResolver(m.Entries)

	currentFolder := ""
	for _, numbered := range numberedEntries {
		entry := numbered.Entry
		if numbered.Folder != currentFolder {
			currentFolder = numbered.Folder
			fmt.Fprintf(&b, "\n## %s\n", currentFolder)
		}
		fmt.Fprintf(&b, "\n### %d. %s\n\n", numbered.Number, entry.Title)
		fmt.Fprintf(&b, "key: `%s` | mode: `%s` | tags: %s | size: %s\n\n", entry.Key, entry.Mode, inlineTags(entry.Tags), sizeMarker(entry))
		if entry.Summary == "" {
			b.WriteString("Summary: none\n\n")
		} else {
			b.WriteString(suffixSummaryWikiLinks(entry.Summary, entry.Key, linkResolver, numberByKey))
			b.WriteString("\n\n")
		}
		fmt.Fprintf(&b, "Headings: %s\n", inlineHeadings(entry.Headings))
	}

	b.WriteString("\n---\n\n")
	fmt.Fprintf(&b, "Tag frequency: %s\n", tagFrequency(m.Tags))
	fmt.Fprintf(&b, "Tool files: %s\n", inlineToolFiles(toolFiles))
	return b.Bytes()
}

func suffixSummaryWikiLinks(summary, currentKey string, resolver *manifest.WikiLinkResolver, numberByKey map[string]int) string {
	var b strings.Builder
	changed := false
	pos := 0

	for pos < len(summary) {
		start := strings.Index(summary[pos:], "[[")
		if start < 0 {
			break
		}
		start += pos

		end := strings.Index(summary[start+2:], "]]")
		if end < 0 {
			break
		}
		end += start + 2

		raw := summary[start+2 : end]
		replacement, ok := suffixedWikiLink(raw, currentKey, resolver, numberByKey)
		if !ok {
			if changed {
				b.WriteString(summary[pos : end+2])
			}
			pos = end + 2
			continue
		}

		if !changed {
			b.Grow(len(summary) + 8)
			b.WriteString(summary[:start])
			changed = true
		} else {
			b.WriteString(summary[pos:start])
		}
		b.WriteString(replacement)
		pos = end + 2
	}

	if !changed {
		return summary
	}
	b.WriteString(summary[pos:])
	return b.String()
}

func suffixedWikiLink(raw, currentKey string, resolver *manifest.WikiLinkResolver, numberByKey map[string]int) (string, bool) {
	inner := strings.TrimSpace(raw)
	target, display, hasDisplay := strings.Cut(inner, "|")
	target = strings.TrimSpace(target)
	display = strings.TrimSpace(display)
	if target == "" || strings.ContainsAny(target, "#^") {
		return "", false
	}

	resolvedKey, ok := resolver.Resolve(currentKey, target)
	if !ok {
		return "", false
	}
	number, ok := numberByKey[resolvedKey]
	if !ok {
		return "", false
	}

	if hasDisplay {
		return fmt.Sprintf("[[%s|%s @ %d]]", target, display, number), true
	}
	return fmt.Sprintf("[[%s @ %d]]", target, number), true
}

func ManifestHash(m manifest.Manifest) string {
	data, err := manifest.Marshal(m)
	if err != nil {
		panic(fmt.Sprintf("marshal manifest for brief hash: %v", err))
	}
	sum := sha256.Sum256(data)
	return fmt.Sprintf("sha256:%x", sum)
}

func splitKey(key string) (folder, name string) {
	clean := path.Clean(key)
	folder = path.Dir(clean)
	if folder == "." {
		folder = RootFolder
	}
	return folder, path.Base(clean)
}

func folderSortKey(folder string) string {
	if folder == RootFolder {
		return ""
	}
	return folder
}

func inlineTags(tags []string) string {
	if len(tags) == 0 {
		return "none"
	}

	sorted := append([]string(nil), tags...)
	sort.Strings(sorted)
	parts := make([]string, 0, len(sorted))
	for _, tag := range sorted {
		parts = append(parts, "`"+tag+"`")
	}
	return strings.Join(parts, ", ")
}

func inlineHeadings(headings []manifest.Heading) string {
	if len(headings) == 0 {
		return "none"
	}

	parts := make([]string, 0, len(headings))
	for _, heading := range headings {
		parts = append(parts, heading.Text)
	}
	return strings.Join(parts, "; ")
}

func sizeMarker(entry manifest.Entry) string {
	lines := entry.Lines
	if lines < 0 {
		lines = 0
	}
	return fmt.Sprintf("%s / %d lines", friendlyBytes(entry.Bytes), lines)
}

func friendlyBytes(bytes int64) string {
	if bytes <= 0 {
		return "0B"
	}
	if bytes < 1000 {
		return fmt.Sprintf("%dB", bytes)
	}
	if bytes < 1000*1000 {
		return friendlyUnit(float64(bytes)/1000, "k")
	}
	return friendlyUnit(float64(bytes)/(1000*1000), "M")
}

func friendlyUnit(value float64, suffix string) string {
	if value < 10 {
		text := fmt.Sprintf("%.1f", value)
		text = strings.TrimSuffix(text, ".0")
		return text + suffix
	}
	return fmt.Sprintf("%.0f%s", value, suffix)
}

func tagFrequency(tags map[string]int) string {
	if len(tags) == 0 {
		return "none"
	}

	names := make([]string, 0, len(tags))
	for tag := range tags {
		names = append(names, tag)
	}
	sort.Strings(names)

	parts := make([]string, 0, len(names))
	for _, tag := range names {
		parts = append(parts, fmt.Sprintf("%s=%d", tag, tags[tag]))
	}
	return strings.Join(parts, ", ")
}

func inlineToolFiles(files []string) string {
	if len(files) == 0 {
		return "none"
	}

	sorted := append([]string(nil), files...)
	sort.Strings(sorted)
	return strings.Join(sorted, ", ")
}
