package brief

import (
	"bytes"
	"os"
	"path/filepath"
	"testing"

	"github.com/tpisel/memento/internal/manifest"
	"github.com/tpisel/memento/internal/markdown"
	"github.com/tpisel/memento/internal/vault"
)

func TestRenderProducesDeterministicMarkdownProjection(t *testing.T) {
	m := manifest.Manifest{
		Entries: []manifest.Entry{
			{
				Key:     "notes/alpha.md",
				Title:   "Alpha <Beta>",
				Summary: "Summary with <angle> & ampersand.",
				Tags:    []string{"memento", "brief"},
				Mode:    markdown.ModeReadOnly,
				Headings: []manifest.Heading{
					{Level: 2, Text: "Context", Slug: "context"},
					{Level: 3, Text: "Decision & Tradeoffs", Slug: "decision-tradeoffs"},
				},
				SummaryStale: true,
				Links: manifest.Links{
					Out: []manifest.OutLink{{Target: "other.md", Type: "wiki", Resolved: true}},
				},
			},
			{
				Key:     "zeta.md",
				Title:   "Zeta",
				Summary: "",
				Tags:    []string{},
				Mode:    markdown.ModeAppendOnly,
			},
		},
		Tags: map[string]int{
			"brief":   1,
			"memento": 1,
		},
	}

	first := Render(m)
	second := Render(m)
	if !bytes.Equal(first, second) {
		t.Fatalf("Render output changed between runs:\nfirst:\n%s\nsecond:\n%s", first, second)
	}

	want := `---
mode: read-only
---
<!-- Auto-generated by memento compile. Edits will be overwritten. -->

# Memento Brief

## Alpha <Beta>

key: ` + "`notes/alpha.md`" + ` | mode: ` + "`read-only`" + ` | tags: ` + "`brief`" + `, ` + "`memento`" + `

Summary with <angle> & ampersand.

Headings: Context; Decision & Tradeoffs

## Zeta

key: ` + "`zeta.md`" + ` | mode: ` + "`append-only`" + ` | tags: none

Summary: none

Headings: none

---

Tag frequency: brief=1, memento=1
Tool files: none
`
	if string(first) != want {
		t.Fatalf("Render() =\n%s\nwant:\n%s", first, want)
	}

	for _, forbidden := range []string{"summary_stale", "links", "slug", "\\u003c", "\\u003e", "\\u0026"} {
		if bytes.Contains(first, []byte(forbidden)) {
			t.Fatalf("Render() contains forbidden %q:\n%s", forbidden, first)
		}
	}
}

func TestRenderWithToolFilesListsDetectedFiles(t *testing.T) {
	got := string(RenderWithToolFiles(manifest.Manifest{}, []string{"_memento/review.md", "_memento/writing.md"}))

	if !bytes.Contains([]byte(got), []byte("Tool files: _memento/review.md, _memento/writing.md\n")) {
		t.Fatalf("RenderWithToolFiles() =\n%s\nwant tool file footer", got)
	}
}

func TestDetectToolFilesHandlesMissingNamespace(t *testing.T) {
	files, err := DetectToolFiles(vault.Vault{Root: t.TempDir()})
	if err != nil {
		t.Fatalf("DetectToolFiles() error = %v, want nil", err)
	}
	if len(files) != 0 {
		t.Fatalf("DetectToolFiles() = %#v, want empty", files)
	}
}

func TestDetectToolFilesListsKnownFiles(t *testing.T) {
	root := t.TempDir()
	dir := filepath.Join(root, vault.ToolDirName)
	if err := os.MkdirAll(dir, 0o755); err != nil {
		t.Fatalf("mkdir tool dir: %v", err)
	}
	for _, name := range []string{"writing.md", "review.md", "notes.md"} {
		if err := os.WriteFile(filepath.Join(dir, name), []byte("# "+name+"\n"), 0o644); err != nil {
			t.Fatalf("write %s: %v", name, err)
		}
	}

	files, err := DetectToolFiles(vault.Vault{Root: root})
	if err != nil {
		t.Fatalf("DetectToolFiles() error = %v, want nil", err)
	}
	want := []string{"_memento/review.md", "_memento/writing.md"}
	if len(files) != len(want) {
		t.Fatalf("DetectToolFiles() = %#v, want %#v", files, want)
	}
	for i := range want {
		if files[i] != want[i] {
			t.Fatalf("DetectToolFiles() = %#v, want %#v", files, want)
		}
	}
}
