package brief

import (
	"bytes"
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/tpisel/memento/internal/manifest"
	"github.com/tpisel/memento/internal/vault"
)

const Banner = "<!-- Auto-generated by memento compile. Edits will be overwritten. -->"

var toolConsumedFileNames = []string{"audit.md", "review.md", "writing.md"}

// DetectToolFiles returns known tool-consumed files present in the vault's
// human-readable tool namespace.
func DetectToolFiles(v vault.Vault) ([]string, error) {
	dir := filepath.Join(v.Root, vault.ToolDirName)
	info, err := os.Stat(dir)
	if err != nil {
		if errors.Is(err, os.ErrNotExist) {
			return nil, nil
		}
		return nil, fmt.Errorf("stat %s: %w", vault.ToolDirName, err)
	}
	if !info.IsDir() {
		return nil, nil
	}

	files := []string{}
	for _, name := range toolConsumedFileNames {
		path := filepath.Join(dir, name)
		info, err := os.Stat(path)
		if err != nil {
			if errors.Is(err, os.ErrNotExist) {
				continue
			}
			return nil, fmt.Errorf("stat %s: %w", filepath.ToSlash(filepath.Join(vault.ToolDirName, name)), err)
		}
		if info.IsDir() {
			continue
		}
		files = append(files, filepath.ToSlash(filepath.Join(vault.ToolDirName, name)))
	}
	return files, nil
}

// Render returns the agent-facing markdown projection of a manifest.
func Render(m manifest.Manifest) []byte {
	return RenderWithToolFiles(m, nil)
}

// RenderWithToolFiles returns the agent-facing markdown projection of a manifest
// and includes detected tool-consumed files in the footer.
func RenderWithToolFiles(m manifest.Manifest, toolFiles []string) []byte {
	var b bytes.Buffer
	b.WriteString("---\nmode: read-only\n---\n")
	b.WriteString(Banner)
	b.WriteString("\n\n# Memento Brief\n")

	entries := append([]manifest.Entry(nil), m.Entries...)
	sort.Slice(entries, func(i, j int) bool {
		return entries[i].Key < entries[j].Key
	})

	for _, entry := range entries {
		fmt.Fprintf(&b, "\n## %s\n\n", entry.Title)
		fmt.Fprintf(&b, "key: `%s` | mode: `%s` | tags: %s | size: %s\n\n", entry.Key, entry.Mode, inlineTags(entry.Tags), sizeMarker(entry))
		if entry.Summary == "" {
			b.WriteString("Summary: none\n\n")
		} else {
			b.WriteString(entry.Summary)
			b.WriteString("\n\n")
		}
		fmt.Fprintf(&b, "Headings: %s\n", inlineHeadings(entry.Headings))
	}

	b.WriteString("\n---\n\n")
	fmt.Fprintf(&b, "Tag frequency: %s\n", tagFrequency(m.Tags))
	fmt.Fprintf(&b, "Tool files: %s\n", inlineToolFiles(toolFiles))
	return b.Bytes()
}

func inlineTags(tags []string) string {
	if len(tags) == 0 {
		return "none"
	}

	sorted := append([]string(nil), tags...)
	sort.Strings(sorted)
	parts := make([]string, 0, len(sorted))
	for _, tag := range sorted {
		parts = append(parts, "`"+tag+"`")
	}
	return strings.Join(parts, ", ")
}

func inlineHeadings(headings []manifest.Heading) string {
	if len(headings) == 0 {
		return "none"
	}

	parts := make([]string, 0, len(headings))
	for _, heading := range headings {
		parts = append(parts, heading.Text)
	}
	return strings.Join(parts, "; ")
}

func sizeMarker(entry manifest.Entry) string {
	lines := entry.Lines
	if lines < 0 {
		lines = 0
	}
	return fmt.Sprintf("%s / %d lines", friendlyBytes(entry.Bytes), lines)
}

func friendlyBytes(bytes int64) string {
	if bytes <= 0 {
		return "0B"
	}
	if bytes < 1000 {
		return fmt.Sprintf("%dB", bytes)
	}
	if bytes < 1000*1000 {
		return friendlyUnit(float64(bytes)/1000, "k")
	}
	return friendlyUnit(float64(bytes)/(1000*1000), "M")
}

func friendlyUnit(value float64, suffix string) string {
	if value < 10 {
		text := fmt.Sprintf("%.1f", value)
		text = strings.TrimSuffix(text, ".0")
		return text + suffix
	}
	return fmt.Sprintf("%.0f%s", value, suffix)
}

func tagFrequency(tags map[string]int) string {
	if len(tags) == 0 {
		return "none"
	}

	names := make([]string, 0, len(tags))
	for tag := range tags {
		names = append(names, tag)
	}
	sort.Strings(names)

	parts := make([]string, 0, len(names))
	for _, tag := range names {
		parts = append(parts, fmt.Sprintf("%s=%d", tag, tags[tag]))
	}
	return strings.Join(parts, ", ")
}

func inlineToolFiles(files []string) string {
	if len(files) == 0 {
		return "none"
	}

	sorted := append([]string(nil), files...)
	sort.Strings(sorted)
	return strings.Join(sorted, ", ")
}
