package brief

import (
	"bytes"
	"os"
	"path/filepath"
	"testing"

	"github.com/tpisel/memento/internal/manifest"
	"github.com/tpisel/memento/internal/markdown"
	"github.com/tpisel/memento/internal/vault"
)

func TestRenderProducesDeterministicMarkdownProjection(t *testing.T) {
	m := manifest.Manifest{
		Entries: []manifest.Entry{
			{
				Key:     "notes/alpha.md",
				Title:   "Alpha <Beta>",
				Summary: "Summary with <angle> & ampersand.",
				Bytes:   342,
				Lines:   32,
				Tags:    []string{"memento", "brief"},
				Mode:    markdown.ModeReadOnly,
				Headings: []manifest.Heading{
					{Level: 2, Text: "Context", Slug: "context"},
					{Level: 3, Text: "Decision & Tradeoffs", Slug: "decision-tradeoffs"},
				},
				SummaryStale: true,
				Links: manifest.Links{
					Out: []manifest.OutLink{{Target: "other.md", Type: "wiki", Resolved: true}},
				},
			},
			{
				Key:     "notes/beta.md",
				Title:   "Beta",
				Summary: "A compact note.",
				Bytes:   1234,
				Lines:   7,
				Tags:    []string{"brief"},
				Mode:    markdown.ModeAppendOnly,
			},
			{
				Key:     "notes/gamma.md",
				Title:   "Gamma",
				Summary: "A larger note.",
				Bytes:   12345,
				Lines:   250,
				Tags:    []string{"memento"},
				Mode:    markdown.ModeAppendOnly,
			},
			{
				Key:     "zeta.md",
				Title:   "Zeta",
				Summary: "",
				Tags:    []string{},
				Mode:    markdown.ModeAppendOnly,
			},
		},
		Tags: map[string]int{
			"brief":   2,
			"memento": 2,
		},
	}

	first := Render(m)
	second := Render(m)
	if !bytes.Equal(first, second) {
		t.Fatalf("Render output changed between runs:\nfirst:\n%s\nsecond:\n%s", first, second)
	}

	want := `---
mode: read-only
---
> [!caution] Auto-generated by ` + "`memento compile`" + `
> Any edits to this file will be overwritten on the next compile run.

# Memento Brief

## Alpha <Beta>

key: ` + "`notes/alpha.md`" + ` | mode: ` + "`read-only`" + ` | tags: ` + "`brief`" + `, ` + "`memento`" + ` | size: 342B / 32 lines

Summary with <angle> & ampersand.

Headings: Context; Decision & Tradeoffs

## Beta

key: ` + "`notes/beta.md`" + ` | mode: ` + "`append-only`" + ` | tags: ` + "`brief`" + ` | size: 1.2k / 7 lines

A compact note.

Headings: none

## Gamma

key: ` + "`notes/gamma.md`" + ` | mode: ` + "`append-only`" + ` | tags: ` + "`memento`" + ` | size: 12k / 250 lines

A larger note.

Headings: none

## Zeta

key: ` + "`zeta.md`" + ` | mode: ` + "`append-only`" + ` | tags: none | size: 0B / 0 lines

Summary: none

Headings: none

---

Tag frequency: brief=2, memento=2
Tool files: none
`
	if string(first) != want {
		t.Fatalf("Render() =\n%s\nwant:\n%s", first, want)
	}

	if !bytes.Contains(first, []byte("> [!caution]")) {
		t.Fatalf("Render() missing Obsidian callout marker:\n%s", first)
	}

	for _, forbidden := range []string{"<!-- Auto-generated", "summary_stale", "links", "slug", "\\u003c", "\\u003e", "\\u0026"} {
		if bytes.Contains(first, []byte(forbidden)) {
			t.Fatalf("Render() contains forbidden %q:\n%s", forbidden, first)
		}
	}
}

func TestRenderWithToolFilesListsDetectedFiles(t *testing.T) {
	got := string(RenderWithToolFiles(manifest.Manifest{}, []string{"_memento/review.md", "_memento/writing.md"}))

	if !bytes.Contains([]byte(got), []byte("Tool files: _memento/review.md, _memento/writing.md\n")) {
		t.Fatalf("RenderWithToolFiles() =\n%s\nwant tool file footer", got)
	}
}

func TestFriendlyBytes(t *testing.T) {
	tests := map[int64]string{
		0:       "0B",
		342:     "342B",
		1234:    "1.2k",
		12345:   "12k",
		1400000: "1.4M",
	}

	for bytes, want := range tests {
		if got := friendlyBytes(bytes); got != want {
			t.Fatalf("friendlyBytes(%d) = %q, want %q", bytes, got, want)
		}
	}
}

func TestDetectToolFilesHandlesMissingNamespace(t *testing.T) {
	files, err := DetectToolFiles(vault.Vault{Root: t.TempDir()})
	if err != nil {
		t.Fatalf("DetectToolFiles() error = %v, want nil", err)
	}
	if len(files) != 0 {
		t.Fatalf("DetectToolFiles() = %#v, want empty", files)
	}
}

func TestDetectToolFilesListsKnownFiles(t *testing.T) {
	root := t.TempDir()
	dir := filepath.Join(root, vault.ToolDirName)
	if err := os.MkdirAll(dir, 0o755); err != nil {
		t.Fatalf("mkdir tool dir: %v", err)
	}
	for _, name := range []string{"writing.md", "review.md", "notes.md"} {
		if err := os.WriteFile(filepath.Join(dir, name), []byte("# "+name+"\n"), 0o644); err != nil {
			t.Fatalf("write %s: %v", name, err)
		}
	}

	files, err := DetectToolFiles(vault.Vault{Root: root})
	if err != nil {
		t.Fatalf("DetectToolFiles() error = %v, want nil", err)
	}
	want := []string{"_memento/review.md", "_memento/writing.md"}
	if len(files) != len(want) {
		t.Fatalf("DetectToolFiles() = %#v, want %#v", files, want)
	}
	for i := range want {
		if files[i] != want[i] {
			t.Fatalf("DetectToolFiles() = %#v, want %#v", files, want)
		}
	}
}
